services:
  doodle_battery_service:
    image: "doodle_battery_service:latest"
    platform: "linux/arm64"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      # Mount payload credentials.
      - /opt/payload_credentials/payload_guid_and_secret:/payload_guid_and_secret
      - /persist/opt/doodle_rpc_credentials:/doodle_rpc_credentials
    command: 192.168.50.3 --port 51707 --host-ip 192.168.50.5 --payload-credentials-file /payload_guid_and_secret
    deploy:
      resources:
        limits:
          memory: "512M"
    oom_score_adj: 1000
