name: Build Doodle Configurator Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller paramiko

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed core_io_doodle_configurator.py

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: config-tool-${{ matrix.os }}
          path: |
            dist/core_io_doodle_configurator*
